# [Info]
site_name: cani Docs
site_url: http://localhost:8000
site_author: cani

#[UI]
theme:
  name: material
  # custom_dir: docs/voerrides
  # font:
  #   text: Bitter
  #   code: 'Roboto Mono'
  logo: https://s1.imagehub.cc/images/2024/02/02/91a767e93d1a344e44c69936464c583e.png
  features: 
    # - navigation.instant
    - annouce.dismiss # 呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.instant.progress 
    - navigation.tabs # 顶级部分呈现在上面标题下方的菜单层级中
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.expand
    - navigation.indexes
    - toc.integrate

    - search.suggest
    - search.highlight

    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.action.view
  language: zh 
  palette:
    # Palette for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: grean
    # Palette for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: lime
  icon: 
    repo: material/github
  
extra:
  generator: false

plugins:
  - search
  - blog:
      post_date_format: full
      draft: true
      draft_if_future_date: true
      post_readtime: true
      post_readtime_words_per_minute: 265
      post_url_format: "{date}/{slug}"
      pagination_url: "page/{page}"

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
          # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: "\ue157"

# [Navigtion]
nav:
  - 主页: index.md
  - 文档:
    - 快速开始: build.md
    